service: reactApiLambda

plugins:
  #Required when running in UTC+8, with .env document
  - serverless-dotenv-plugin

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: default
  region: ap-east-1
  iam:
    role:
      statements:
          #Apply below policies to all to be built lambda functions
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:ap-east-1:066529494542:table/testjoblist
          #CloudWatch policies for allowing log output
        - Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:ap-east-1:066529494542:*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
          Resource: "*"

functions:
  list:
    handler: lambda/list.hello
    events:
      - http:
          path: /
          method: get
          cors: true
  update:
    handler: lambda/update.handler
    events:
      - http:
          path: /update
          method: post
          cors: true
  delete:
    handler: lambda/delete.handler
    events:
      - http:
          path: /delete
          method: delete
          cors: true
