service: reactApiLambda

# plugins:
#   #Required when running in UTC+8, with .env document
#   - serverless-dotenv-plugin

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.7
  environment:
    vrecTableENV: { "Ref": "vrecTable" }
    orgTableENV: { "Ref": "orgTable" }
  profile: default
  region: us-east-1
  iam:
    role:
      statements:
        #Apply below policies to all to be built lambda functions
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt vrecTable.Arn
            - !GetAtt orgTable.Arn
          #CloudWatch policies for allowing log output
        - Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
          Resource: "*"

functions:
  create:
    handler: lambda/create.lambda_handler
    events:
      - http:
          path: /create
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - Access-Control-Allow-Origin
    environment:
      TABLE_NAME: !Ref vrecTable
  authenticate:
    handler: lambda/authenticate.lambda_handler
    events:
      - http:
          path: /authenticate
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - Access-Control-Allow-Origin
    environment:
      TABLE_NAME: !Ref vrecTable
  retrieve:
    handler: lambda/retrieve.lambda_handler
    events:
      - http:
          path: /retrieve
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
              - Access-Control-Allow-Origin
    environment:
      TABLE_NAME: !Ref orgTable

resources:
  Resources:
    vrecTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        #On Demand Billing
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    orgTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: org
            AttributeType: S
        #On Demand Billing
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: org
            KeyType: HASH
