service: reactApiLambda

plugins:
  - serverless-dotenv-plugin

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: default
  region: ap-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:ap-east-1:066529494542:table/testjoblist
        - Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:ap-east-1:066529494542:*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
          Resource: "*"

functions:
  list:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true

